development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: mfdev
  suffix: development
  username: test
  password: test

production:
  protocol: 'https'
  host: gagan.cloudant.com
  port: 443
  prefix: mfdev
  suffix: production
  username:
  password: 