development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: summary
  suffix: development
  username: test
  password: test

test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  host: localhost
  port: 5984
  prefix: summary
  suffix: production
  username: root
  password: 123