development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: summary2
  suffix: development
  username: test
  password: test

test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  host: gagan.cloudant.com
  port: 443
  prefix: summary
  suffix: production
  username:
  password: 